### ISSUE TITLE
Set TTL for enqueue

### ISSUE THREAD

**Issue by mentalbrew** [ui/django-rq#107]
I'm trying to set the TTL for jobs but cannot find a way to do so. Currently I've tried the following:

```
enqueue(func, arg1, ttl=1)

enqueue(func=func, args=(arg1,), ttl=1)
```

Does django-rq support TTL for jobs?

**Comment by selwin** [comment]
Not yet, but we should support whatever argument that RQ supports. Pull request welcome :)

**Comment by smaccona** [comment]
I went to create a PR for this, but on examination it looks like `ttl` should be passed directly through to RQ's `enqueue` call itself as a kwarg, and RQ should pop it off.

In my case, the culprit was RQ itself - the build I had installed didn't have `ttl` support. You may want to check your own installed RQ to see if `ttl` is being checked for - it was only added a few months ago (see https://github.com/nvie/rq/commit/8a3fd91e2ec2bc09af30652f3ed9b8ce846d8922).

**Comment by agconti** [comment]
@mentalbrew 
Setting the `ttl` this way works like a charm for me:
```python
django_rq.enqueue(func, arg1, arg2, { "result_ttl": 1 })
```

**Comment by mbodock** [comment]
I guess https://github.com/nvie/rq/issues/502 fixes.
At least in my tests.

@agconti different things, RESULT_TTL is for the result after job execution, and TTL should make redis expires the key, without the worker.

**Comment by agconti** [comment]
@mbodock ahh, thanks for setting that one straight.

**Comment by selwin** [comment]
Closed as this is not an issue in django-rq itself
