### ISSUE TITLE
Queues are not passed via command line

### ISSUE THREAD

**Issue by aplanas** [ui/django-rq#180]
There is a missing `parser.add_argument('queues', nargs='+', type=str)` line. Now if I execute this (as documented):

    manage.py rqworker high default low

I get the error:

    manage.py rqworker: error: unrecognized arguments: high default low

**Comment by juanfont** [comment]
I am having the same issue. I guess it is related to this change made to support Django 1.10 https://github.com/ui/django-rq/commit/a13969d16985bb90a31947ccaed3020a7d9fa1c4

**Comment by kegan** [comment]
I am having the same issue with `Django 1.10`, `django-rq 0.91`.

```
File "xxx/lib/python3.4/site-packages/django_rq/management/commands/rqworker.py", line 35, in <module>
  class Command(BaseCommand):
File "xxx/lib/python3.4/site-packages/django_rq/management/commands/rqworker.py", line 43, in Command
  option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

```

**Comment by juanfont** [comment]
@kegan django-rq 0.9.1 is from May (https://github.com/ui/django-rq/commits/v0.9.1) and it had no support for Django 1.10. If you update to master with `pip install --upgrade git+https://github.com/ui/django-rq` you will get the same error @aplanas and I are getting.

**Comment by lastkarrde** [comment]
Hi

This bug[0] was introduced in v0.9.2 but this fix has still not been incorporated into an official release. Can a v0.9.3 release be made (pypi) which incorporates this fix?

I have a project that I'm wanting to upgrade to Django 1.10 but cannot due to this bug fix not being in an official release.

Thanks

 [0] https://github.com/ui/django-rq/commit/a13969d16985bb90a31947ccaed3020a7d9fa1c4

**Comment by selwin** [comment]
Will tey to cut a new release this weekend. Sorry for the wait.

**Comment by selwin** [comment]
I just tagged 0.9.3 on PyPI. Sorry for the wait everyone!
