### ISSUE TITLE
Django-rq slow interface

### ISSUE THREAD

**Issue by lucastamoios** [ui/django-rq#231]
I have 4 worker servers orchestrated by docker swarm, running more than 600 workers. I noticed the interface `rq_home` got slow because of the number of workers.

When running the function `django_rq.views.stats` alone, it took me 10 seconds to respond. This part in special seems slower

    all_workers = Worker.all(connection=connection)

This is really annoying me because we depend on the interface. Is there any way to get through this slowness?

**Comment by selwin** [comment]
The code in `Worker.all()` repeatedly calls `Worker.find_by_key`, each resulting in a few Redis calls.

I have opened an issue to address this here: https://github.com/nvie/rq/issues/822 . Addressing the first part of that issue should significantly improve the responsiveness of `rq_home`. Addressing the second part should make `rq_home` load instantly because it should only make one Redis `scard` call to get the number of workers.
